FROM httpd:alpine

COPY html/ /usr/local/apache2/htdocs/

# To build this image use
# docker image build -t training:httpd1 .

# Then check the history
# docker history training:httpd1

# Run it with
# docker container run --name httpd1 -p 90:80 -d training:httpd1

# Check it out in the browser
# http://localhost:90



 
