version: '3'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=NobleProg
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    ports:
      - 3306:3306
    networks:
      - net
  apache:
    depends_on:
      - mysql
    image: wordpress:latest
    volumes:
      - html:/var/www/html
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
    networks:
      - net
volumes:
  mysql_data:
  html:
networks:
  net:
